package com.cs.dipocketback.pojo.report;

public enum ReportType {

    MONITORING,
    MONITORING_OFFLINE_CARD_TRANSACTION,
    MONITORING_OFFLINE_LARGE_AMOUNTS,
    MONITORING_OFFLINE_TOP_UP,
    MONITORING_OFFLINE_BANK_TRANSFER,
    MONITORING_OFFLINE_CUSTOMER_NOTIFICATION,
    FESTIVAL_CASHIER,
    FESTIVAL_EFOTT,
    FESTIVAL_SDD,
    GBG,
    BANKTRANSFER_CIB_OUT,
    BANKTRANSFER_CIB_IN,
    GPS_SETTLEMENT_ALL,
    GPS_SETTLEMENT_FOR_PEAK,
    UP_AND_GO_OUT,
    UP_AND_GO_IN

}
