//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.09 at 01:24:14 PM EET 
//


package com.cs.dipocketback.pojo.tds.v1.resp;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "backgroundPares", propOrder = {
    "paresStatus",
    "paresCommand"
})
public class BackgroundPares {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String paresStatus;
//    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
//    @XmlSchemaType(name = "normalizedString")
//    protected List<String> paresCommand;

    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String paresCommand;

    public String getParesStatus() {
        return paresStatus;
    }

    public void setParesStatus(String value) {
        this.paresStatus = value;
    }

//    public List<String> getParesCommand() {
//        if (paresCommand == null) {
//            paresCommand = new ArrayList<String>();
//        }
//        return this.paresCommand;
//    }


    public String getParesCommand() {
        return paresCommand;
    }

    public void setParesCommand(String paresCommand) {
        this.paresCommand = paresCommand;
    }
}
