package com.cs.dipocketback.pojo.bacca;

public enum BaccaNavigationStatus {
    SHOW_START_REGISTRATION,
    SHOW_LOGIN_PAGE,
    SHOW_LOGIN_PAGE_WITHOUT_PESEL,
    SHOW_CREATE_ACCOUNT,
    SHOW_POLICIES,
    NO_BACCA_CLIENT,
    FULL_ACCOUNT_VERIFICATION_REQUIRED;
}
